# Generated by Django 5.2.6 on 2025-09-25 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_is',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
