# Generated by Django 5.2.6 on 2025-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_college_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
