# Generated by Django 5.2.6 on 2025-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_hype_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('total_used', models.IntegerField(default=0)),
                ('Rank', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feed Tag Statistic',
                'verbose_name_plural': 'Feed Tag Statistics',
                'ordering': ['-Rank', '-total_used'],
            },
        ),
    ]
