# Generated by Django 5.2.6 on 2025-10-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_feed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
