# Generated by Django 5.2.6 on 2025-10-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_comment_options_remove_comment_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
