# Generated by Django 5.2.6 on 2025-10-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='feed_types',
        ),
    ]
